name: deploy-game
run-name: ${{ github.actor }} is deploying WizGame
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-build-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Get correct Target
      - run: rustup target add wasm32-unknown-unknown
      # Add wasm-bindgen
      - uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: "latest"
      # Build
      # TODO : CACHE RUST DEPS https://github.com/marketplace/actions/rust-cache
      - run: bash build_wasm.sh
      # Zip
      - run: zip -r wbindgen.zip wbindgen
      # Deploy
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: wiz-game
          ITCH_USER: Ianplatt
          PACKAGE: wbindgen.zip
